package com.makershub.enums;

public enum NotificationType {
    BID_RECEIVED, BID_ACCEPTED, ORDER_STATUS_UPDATE, PAYMENT_RECEIVED, ESCROW_RELEASED, DISPUTE_OPENED, DISPUTE_RESOLVED, MESSAGE_RECEIVED, VERIFICATION_STATUS, REVIEW_RECEIVED
}
